### ISSUE TITLE
8.2 database changes

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#135] opened 2019-04-17 00:57 UTC
I’m posting an issue without a current solution, just as a heads up: CascLib currently doesn’t work with patch 8.2. There are actually two problems:

(i) root file changes. According to Martin Benjamins: “there are semi-minor changes to the root file to support filenames becoming optional that i'm sure will be on wiki later this week/over the weekend“

(ii) most new files are being added without names - for most most new files in 8.2 and above it’ll no longer be possible to find them by their real names and they’ll have to be treated purely as numbers. This is a nightmare and I don’t know the best way to handle it. Maybe as we determine the purpose of a file we can make up a name for it and have a database that maps file IDs to our made up names. This might be better centralised, so multiple projects don’t end up calling models different things.

**Comment by ladislav-zezula** [comment] 2019-04-17 06:36
I'll install 8.2 and try to solve the first point at least.

**Comment by WainPetopia** [comment] 2019-04-17 08:47
Thank you.  Much appreciated :)

**Comment by WainPetopia** [comment] 2019-04-19 17:58
I assume these are the CASC changes:
https://wowdev.wiki/index.php?title=CASC&type=revision&diff=26687&oldid=26275

A few people are working on a file naming system for new files. They’re aiming to automate as much of it as they can. Hopefully there’ll be something released soon.

**Comment by ladislav-zezula** [comment] 2019-04-21 10:58
From what I saw in 8.2 ROOT file, the structure seems to be the same: There is an array of
0x00 - 0x10 bytes - ContentKey
0x10 - 0x08 bytes - Jenkins Hash of the file name

For file names, CascLib uses external listfile since WoW 6.0.
Could you be more specific about what does not work?

**Comment by tomrus88** [comment] 2019-04-21 23:38
> From what I saw in 8.2 ROOT file, the structure seems to be the same
They aren't the same. There's now 12 bytes header present, and file is split into 2 sections, first section has new format where FileNameHash isn't present and second section is much smaller and has old format.

**Comment by ladislav-zezula** [comment] 2019-04-22 18:39
Ah. Its not on live yet, its on PTR only.

**Comment by WainPetopia** [comment] 2019-04-22 19:04
Ah, sorry if I wasn't clear! 8.2 is on the PTR now, 8.1.5 is live.

Also, in 8.2 filenames can no longer be linked to file IDs using the hash function (or whatever it is that casclib uses), so instead people are working on a CSV version of listfile, with fileID ; fileName pairs. Newer files will have to have user-created names. So CascView.exe will probably have to use something like that for 8.2 and above. You can download a preliminary version of listfile.csv on Martin Benjamins' site, if you want to use it for testing: https://wow.tools/files/#search=&page=1&sort=0&desc=asc  It's still a work in progress.  Thanks :)

**Comment by ladislav-zezula** [comment] 2019-04-22 19:49
> Ah, sorry if I wasn't clear! 8.2 is on the PTR now, 8.1.5 is live.
No problem.

> so instead people are working on a CSV version of listfile, with fileID ; fileName pairs. Newer files will have to have user-created names.
I'll look at the CSV version of the listfile and make some preliminary updates to CascLib.

**Comment by WainPetopia** [comment] 2019-04-26 09:57
Is there already a way of telling if a file ID is valid? I couldn't see how to check that but I probably stupidly missed it. If it's not there we'll probably need it.

Currently WMV reads the listfile and queries CascLib by filename to get the ID. If the file name is invalid it returns -1.  In 8.2+ we just add all names and IDs from the csv, but I still need to run a check to ensure the files are actually in the CASC database.

**Comment by ladislav-zezula** [comment] 2019-04-26 10:42
Ok, this is gonna be a bit of problem. In WoW 8.2, the only thing that works is open by FileDataId.

**Comment by WainPetopia** [comment] 2019-04-26 11:00
I guess that would work for us. I can just attempt to open each file by ID and remove file IDs that don't open.

**Comment by ladislav-zezula** [comment] 2019-04-26 11:05
Searching the archive (even without listfile) *will* also give FileDataId for each file found. Could that possibly help?

**Comment by WainPetopia** [comment] 2019-04-26 11:54
I'm not yet sure how to do that (I haven't worked much with CascLib before) but it sounds like that would work. I just need to be able to filter out any bad IDs from our new listfile (which can happen if it contains files only found in other game versions). Otherwise WMV would display listings for models that aren't actually there. Any function I can use to do that would be handy.

**Comment by ladislav-zezula** [comment] 2019-04-26 12:01
If you can't trust the FileDataIds in the listfile, then the only way is to try to open it.

**Comment by WainPetopia** [comment] 2019-04-26 12:22
Can you open by ID currently? WMV always used open by name. Is it maybe CascOpenFileByCKey()?

**Comment by ladislav-zezula** [comment] 2019-04-26 12:29
In the update that's coming as a solution of this issue, yes.

**Comment by Jeromnimo** [comment] 2019-04-26 12:31
@WainPetopia : ladislav is right. In fact, it will be the same philosophy than today, but reversed. Today the check is done for each filename, because we can't trust listfile to be fully relevant. Tomorrow, we have to do the same, but for each filedataId

**Comment by WainPetopia** [comment] 2019-04-26 12:36
Yep, that's what I figured. I just wasn't clear if it was already possible or not.

**Comment by ladislav-zezula** [comment] 2019-04-26 12:37
Also - I plan to remove the CascGetFileId function. Do you guys need it?

**Comment by WainPetopia** [comment] 2019-04-26 12:40
That's better for @Jeromnimo to say, but I can't see a use for it. We can make the new listfile.csv work with older versions of WoW, so I don't think that function will be needed for legacy versions.

**Comment by ladislav-zezula** [comment] 2019-04-26 12:46
The reason behind that is that before, there was a clear mapping between name -> file item which worker like this:
```
FileName -> Hash -> Find that hash -> Return that FileDataId
```
Now this is no longer possible, because hashes are often missing. So I see no way to keep it working.

**Comment by Jeromnimo** [comment] 2019-04-26 12:50
I wil have to double check when I will be back home, but as far as I remember, I needed it to generate a file which maps filename/fileId (https://bitbucket.org/wowmodelviewer/wowmodelviewer/src/8a98cedf3c14932f1ec7b0aa15cae3c6fc511fb0/src/ListFileGenerator/?at=default) in order to be able to debug queries, etc. I don't think it is used in WMV production code today. Internal code (except list of available files) is already heavily relying on filedataId on since Blizzard inotruced that notion (because it's the way the files are referenced in db)

**Comment by ladislav-zezula** [comment] 2019-04-26 15:12
Support for World of Warcraft 8.2 added in commit dd6fd36e4474c2693f3928610df4e1595584f2f7

**Comment by WainPetopia** [comment] 2019-04-26 16:22
Awesome! Thank you so much :)

**Comment by WainPetopia** [comment] 2019-04-28 01:34
Just as a follow up - it’s working perfectly. Thanks again!

**Comment by ladislav-zezula** [comment] 2019-05-17 15:36
If anyone has, by any chance, access to the WoW Classic data files and would you be willing to share, I am very interested.

**Comment by WainPetopia** [comment] 2019-05-17 21:30
I haven’t been granted a Classic beta key, sorry. :(

But - if you go to WoW.tools (new site for Marlamin’s tools and lists) you might be able to get them. You may have to register first, if you haven’t already (registration is the same as his old page). I’m not sure what his procedure is for getting entire game databases now. Let me know if you have trouble.

**Comment by Naros** [comment] 2019-07-12 18:20
Just tested this with 8.2 and it doesn't seem even providing the `FileDataId` as the name works.  Has there been more changes that the library is not yet capable of supporting causing this problem?

**Comment by ladislav-zezula** [comment] 2019-07-12 19:59
In 8.2, passing file name for a file without name hash has no sense. You need to pass file data ID as follows:
CascOpenFile(hStorage, CASC_FILE_DATA_ID(666606), 0, 0, &hFile);

**Comment by Naros** [comment] 2019-07-13 06:29
That is exactly what I am doing except `TFileTreeRoot::GetFile` calls `FileTree.FindById(666606)` but that returns `NULL`.  Unless the m2's file-id has changed (which it hasn't according to the listfile), then I'm confused as to why I cannot retrieve the file from storage.

**Comment by ladislav-zezula** [comment] 2019-07-13 19:28
The problem is that it works for me, both in master and in development:
![find-by-id](https://user-images.githubusercontent.com/3244359/61175762-28949300-a5b5-11e9-9607-c7f26fde5daf.png)

**Comment by Naros** [comment] 2019-07-15 04:06
This is the output from running the test:
```
-- "/mnt/wow/Data" -----------------------------------------------------------------------
Warning: File666606.bin: Open error (error code: 0)                                               
TotalTime: 1.0 second(s)                                                                          
Work complete.
```

**Comment by ladislav-zezula** [comment] 2019-07-15 06:29
Could you run CascView on the storage, give it a proper CSV listfile from https://wow.tools/files and see if it gives the same error?

**Comment by Naros** [comment] 2019-07-15 18:15
@ladislav-zezula I tried CascView and I was able to extract the file with no problem.  

To give you some background, I compile on Fedora 29 using CMAKE 3.14.3 and GCC 8.3.1.  I deploy the application as a part of a docker container that accesses the game data over a linux mount to a host machine's directory.  This worked prior to the 8.2 support changes.

I have setup a simple application as follows (perhaps I'm simply doing something wrong?)

    #include "CascLib.h"
   
    int main()
    {
      HANDLE storage;
      if  ( CascOpenStorage( "/mnt/wow/Data", 0, &storage) ) 
      {
        HANDLE file;
        // This call below causes a segmentation fault at CascOpenFile.cpp:96
        // if ( CascOpenFile( storage, CASC_FILE_DATA_ID(666606), 0, 0, &file ) )
        // This causes error #2, file cannot be found
        // if ( CascOpenFile( storage, "666606", 0, 0, &file ) )
        // This also causes error #2, file cannot be found
        if ( CascOpenFile( storage, "File666606.bin", 0, 0, &file ) )
        {
          printf( "Creature\\Firekitty\Firekitty.m2 opened successfully.\n");
          CascCloseFile( file );
        }
        else
        {
          printf( "Failed to open file, Error #%d\n", GetLastError() );
        }
        CascCloseStorage( storage );
      }
      else
      {
        printf( "Failed to open storage, Error #%d\n", GetLastError() );
      }
    }

**Comment by Shauren** [comment] 2019-07-15 18:54
Try one of the two
```
CascOpenFile(storage, CASC_FILE_DATA_ID(666606), 0, CASC_OPEN_BY_FILEID, &file)
```
```
CascOpenFile(storage, "FILE000A2BEE.xxx", 0, 0, &file) // needs to be 8 character long hex
```

**Comment by ladislav-zezula** [comment] 2019-07-15 19:26
I tried your setup program but it still succeeded. Needed to say, `d:\\Hry\\World of Warcraft\\Data` is installation of WoW that is my live installation of WoW.
![image](https://user-images.githubusercontent.com/3244359/61242908-25c9a780-a747-11e9-9e7a-72717d7e291e.png)

**Comment by Naros** [comment] 2019-07-15 19:56
@Shauren I tried both of your approaches and they both yielded Error 2, file not found.  @ladislav-zezula I tried the development branch and same outcome; I'll continue via email.

**Comment by ladislav-zezula** [comment] 2019-07-15 20:26
Must be something specific in your local storage then. We continue off Github and try to figure the problem out.

**Comment by ladislav-zezula** [comment] 2019-07-18 05:41
@Naros I looked at your storage. Your installation includes Classic WoW and WoW 8.2. You are getting the problem because of the two, Classic WoW storage is opened (because it's first in `.build.info`).

You are not seeing this error in CascView, because it gives you selection. To do the same in CascLib, you need to pass specification in the storahe name like this:
```
CascOpenStorage("/mnt/wow/Data:wow", 0, &storage);
```
If you don't, CascLib will open the default one, which is whichever is the first in 'build.info.

And indeed, in the classic WoW, that Fire Kitty is not present.

Could you check and confirm that it works?

**Comment by Naros** [comment] 2019-07-18 15:14
Using the `:wow` designation did open the file.

**Comment by ladislav-zezula** [comment] 2019-07-18 16:38
Cool. Closing the issue.

**Closed by ladislav-zezula** 2019-07-18 16:38 UTC
