### ISSUE TITLE
Cannot open include file 'resource.h' in CascLib_dll

### ISSUE THREAD

**Issue by herrvigg** [ladislav-zezula/CascLib#202] opened 2021-08-15 11:48 UTC
After upgrading to toolset v142 in VS19 (#201), the main CascLib project and CascLib_test build correctly but not `CascLib_dll`.

```
RC1015 cannot open include file 'resource.h'.	CascLib_dll	D:\projects\ExtraCasc\CascLib\src\DllMain.rc	3
```

I don't know yet if this is due to my platform, I don't use the DLL project but I open this issue just to mention what I noticed.

**Comment by ladislav-zezula** [comment] 2021-08-16 06:09
Fixed in https://github.com/ladislav-zezula/CascLib/commit/a9e122e278d6cb74eb6786fcc93269c9fee949e7. Thanks for the report.

**Closed by ladislav-zezula** 2021-08-16 06:09 UTC

**Comment by ladislav-zezula** [comment] 2021-08-16 20:31
Install MFC classes for Visual Studio.

**Comment by herrvigg** [comment] 2021-08-16 21:04
Sounds like a dependency overkill if this works fine with just windows.h ;)

**Comment by ladislav-zezula** [comment] 2021-08-17 06:12
The problem is that resource.h is auto-generated by Visual Studio and tends to be rewritten back when you edit it.
