### ISSUE TITLE
Commit 47bfd4f9 introduced a regression when reading files

### ISSUE THREAD

**Issue by daagaak** [ladislav-zezula/CascLib#14] opened 2015-01-26 21:24 UTC
I've been trying to track down a problem with ToT master in CascLib. If I attempt to extract World\Maps\Azeroth\Azeroth_29_28.adt, ToT produces a file that is 248725 bytes long, previous checkouts produced a file that is 314252 bytes. I noticed that the shorter file is missing several maptile's worth of data.

I bisected the problem down to the following commit.

```
[carbon: (bisect/bad~1) CascLib]$ git bisect bad 
47bfd4f9b0bcd1cd8d3e3169cc1f68994414e8b6 is the first bad commit
commit 47bfd4f9b0bcd1cd8d3e3169cc1f68994414e8b6
Author: unknown <E:\Ladik\Mail>
Date:   Tue Nov 11 15:10:55 2014 +0100

    + Fixed file size handling for ENCODING and ROOT files
```

**Comment by ladislav-zezula** [comment] 2015-01-27 12:21
I checked that in the current CascTest program. CascGetFileSize returns 0x0004cb8c (314252) and the extraction loop extracts 314252 sharp. The code is like this:

        if(CascOpenFile(hStorage, szFileName, 0, 0, &hFile))
        {
            dwFileSize1 = CascGetFileSize(hFile, NULL);

            for(;;)
            {
                DWORD dwBytesRead = 0;

                CascReadFile(hFile, Buffer, sizeof(Buffer), &dwBytesRead);
                if(dwBytesRead == 0)
                    break;

                dwFileSize2 += dwBytesRead;
            }
            
            CascCloseFile(hFile);
        }

**Comment by daagaak** [comment] 2015-01-27 21:12
I will double-check shortly, CascGetFileSize was returning the shorter size for me, though that does indirectly affect how much I attempt to read from the file itself.

**Comment by daagaak** [comment] 2015-01-28 19:07
Ah I see. So I guess I failed to pull to top-of-tree, so I was using some stale master that was broken. The 622c004 commit fixed the bug I was seeing. Sorry for the noise.

**Comment by ladislav-zezula** [comment] 2015-01-29 07:05
It's OK, I am glad that the problem is solved. Closing.

**Closed by ladislav-zezula** 2015-01-29 07:05 UTC
